project:
  type: default
  output-dir: _output

execute:
  echo: true
  warning: false
  message: false
  cache: true
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - theme.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    embed-resources: true
    smooth-scroll: true
    page-layout: full
    fig-cap-location: bottom
    df-print: paged
    link-external-newwindow: true
    include-after-body: includes/footer.html

bibliography: reports/references.bib

# filters:
#   - lightbox  # install with: quarto add quarto-ext/lightbox

